"""proxy config tables

Revision ID: 13687c89f352
Revises: 2413d6dd74a6
Create Date: 2015-09-23 18:46:37.921338

"""

# revision identifiers, used by Alembic.
revision = '13687c89f352'
down_revision = '2413d6dd74a6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    if not engine_name:
        upgrade_()


def downgrade(engine_name):
    if not engine_name:
        downgrade_()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('physical_partition',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cluster_name', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('port', sa.Text(), nullable=False),
    sa.Column('dbname', sa.Text(), nullable=False),
    # sa.Column('remote_user', sa.Text(), nullable=False),
    # sa.Column('password', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_name'], ['cluster.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('ix_unique_physical_partition', 'physical_partition', ['cluster_name', 'host', 'port', 'dbname'], unique=True)
    op.create_table('logical_partition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('physical_partition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['physical_partition'], ['physical_partition.name'], ),
    sa.PrimaryKeyConstraint('id', 'group', 'physical_partition')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logical_partition')
    op.drop_index('ix_unique_physical_partition', table_name='physical_partition')
    op.drop_table('physical_partition')
    op.drop_table('cluster')
    ### end Alembic commands ###

