"""Add ownership_cleanliness_flag

Revision ID: 22ca179a7eb6
Revises: f69a277dfc5
Create Date: 2015-07-17 11:34:50.323445

"""

# revision identifiers, used by Alembic.
revision = '22ca179a7eb6'
down_revision = 'f69a277dfc5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership_cleanliness_flag',
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('owner_id', postgresql.UUID(), nullable=False),
    sa.Column('is_clean', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.Column('hint', postgresql.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('domain', 'owner_id'),
    sa.ForeignKeyConstraint(['hint'], ['case_data.id'], ),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownership_cleanliness_flag')
    ### end Alembic commands ###
