"""Remove case data and case index

Revision ID: 260e1f55c70
Revises: e1935c99018
Create Date: 2015-09-24 14:49:07.578942

"""

# revision identifiers, used by Alembic.
revision = '260e1f55c70'
down_revision = 'e1935c99018'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # TODO: Drop indexes!?
    op.drop_table('case_form')
    op.drop_table('case_index')
    op.drop_table('case_data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_data',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('owner_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('server_modified_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('case_json', postgresql.JSONB(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSONB(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'case_data_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('case_index',
    sa.Column('case_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('referenced_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('referenced_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], [u'case_data.id'], name=u'case_index_case_id_fkey'),
    sa.ForeignKeyConstraint(['referenced_id'], [u'case_data.id'], name=u'case_index_referenced_id_fkey'),
    sa.PrimaryKeyConstraint('case_id', 'identifier', name=u'case_index_pkey')
    )
    op.create_table('case_form',
    sa.Column('case_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('form_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], [u'case_data.id'], name=u'case_form_case_id_fkey'),
    sa.ForeignKeyConstraint(['form_id'], [u'form_data.id'], name=u'case_form_form_id_fkey'),
    sa.PrimaryKeyConstraint('case_id', 'form_id', name=u'case_form_pkey')
    )
    ### end Alembic commands ###
