"""remove foreign key from CaseIndex

Revision ID: e0fe5591b30
Revises: e1935c99018
Create Date: 2015-09-23 16:08:59.583760

"""

# revision identifiers, used by Alembic.
revision = 'e0fe5591b30'
down_revision = 'e1935c99018'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_index', 'referenced_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint(u'case_index_referenced_id_fkey', 'case_index', type_='foreignkey')
    ### end Alembic commands ###


def downgrade(engine_name):
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'case_index_referenced_id_fkey', 'case_index', 'case_data', ['referenced_id'], ['id'])
    op.alter_column('case_index', 'referenced_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    ### end Alembic commands ###
