"""Remove foreign key constraint on OwnershipCleanlinessFlag

Revision ID: e1935c99018
Revises: b7ecb0cbdf9
Create Date: 2015-08-07 13:14:18.786006

"""

# revision identifiers, used by Alembic.
revision = 'e1935c99018'
down_revision = 'b7ecb0cbdf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'ownership_cleanliness_flag_hint_fkey', 'ownership_cleanliness_flag', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'ownership_cleanliness_flag_hint_fkey', 'ownership_cleanliness_flag', 'case_data', ['hint'], ['id'])
    ### end Alembic commands ###
