"""Drop form JSON

Revision ID: f69a277dfc5
Revises: 1cbfd2c4d21e
Create Date: 2015-07-15 11:20:51.411157

"""

# revision identifiers, used by Alembic.
revision = 'f69a277dfc5'
down_revision = '1cbfd2c4d21e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    _upgrade()


def downgrade(engine_name):
    _downgrade()


def _upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_data', 'form_json')
    op.drop_column('form_error', 'form_json')
    ### end Alembic commands ###


def _downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_error', sa.Column('form_json', postgresql.JSONB(), autoincrement=False, nullable=False))
    op.add_column('form_data', sa.Column('form_json', postgresql.JSONB(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
